### ISSUE TITLE
400 on installing using binary

### ISSUE THREAD

**Issue by MehdiNabi8000** [mattermost-community/mattermost-plugin-msteams-meetings#47] opened 2021-03-05 18:29 UTC
Hi,

I am very enthusiastic about using this plugin, as I might be able to continue using MM and avoid switching fully to teams for messaging :D

I tried installing the plugin on a gitlab omnibus provided instance using the .tar.gz 1.0.0 file, and I got a 400 from the server.

Message in the tool is : `Received invalid response from the server.`

400 in FF console  is : `POST https://mattermost.clap-labs.fr/api/v4/plugins -> 400 bad request`.

I tried to use the plugin marketplace as suggested in the install guide, but I could not find the plugin in it (I am using this one `https://api.integrations.mattermost.com/`)

I did not find anything in the logs regarding the issue.

Mattermost Team Edition
Mattermost Version: 5.31.1
Database Schema Version: 5.30.0
Database: postgres

**Comment by aaronrothschild** [comment] 2021-03-10 14:07
Hi @MehdiNabi8000 !  Thank you for your note, we would love to help you avoid using MS teams too :) 

Unfortunately, I have bad news - the Microsoft calendar plugin requires our "E20" paid licence for the plugin to become available in Mattermost.  That is why you are not seeing it in the marketplace.

**Comment by ahmaddanialmohd** [comment] 2021-03-22 23:11
@aaronrothschild I can confirm on my end that the issue is reproducible when I upload the plugin from **System Console > Plugin Management** in which the process failed with a 400 Bad Request.

<img width="1439" alt="upload_plugin" src="https://user-images.githubusercontent.com/49461314/112069483-dcca2780-8ba6-11eb-85c4-7fbd2320b75d.png">

Installing the plugin from marketplace is successful:

<img width="812" alt="marketplace_1" src="https://user-images.githubusercontent.com/49461314/112069515-f0758e00-8ba6-11eb-89a3-d30925a67486.png">

<img width="794" alt="marketplace_2" src="https://user-images.githubusercontent.com/49461314/112069523-f23f5180-8ba6-11eb-84d6-f204c18c67d2.png">

<img width="791" alt="marketplace_3" src="https://user-images.githubusercontent.com/49461314/112069525-f3707e80-8ba6-11eb-937c-23828d434742.png">

**Comment by hanzei** [comment] 2021-05-27 11:28
Hey @MehdiNabi8000,

Did you try installing the plugin from the Marketplace?

**Comment by MehdiNabi8000** [comment] 2021-05-27 12:16
Hey @hanzei , I did not because of this : 

Unfortunately, I have bad news - the Microsoft calendar plugin requires our "E20" paid licence for the plugin to become available in Mattermost. That is why you are not seeing it in the marketplace.

I have not since then tried to make the plugin work, but I will try again in a few days.

Thank you for your interest !

**Comment by Kshitij-Katiyar** [comment] 2024-08-02 10:48
@hanzei @wiggin77  Closing the issue as there is nothing to do here.

**Closed by Kshitij-Katiyar** 2024-08-02 10:48 UTC
Labels: Type/Question
